### ISSUE TITLE
EP ERROR 

### ISSUE THREAD

**Issue by Wolfeyejo** [machineminded/Fooocus-inswapper#25]
**Read Troubleshoot**

[x] I confirm that I have read the [Troubleshoot](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md) guide before making this issue.

**Describe the problem**
*************** EP Error ***************

**Full Console Log**
:\Fooocus-inswapper-main\ldm_patched\ldm\modules\attention.py:325: UserWarning: 1Torch was not compiled with flash attention. (Triggered internally at ..\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:263.)
  out = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=mask, dropout_p=0.0, is_causal=False)
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [01:24<00:00, 10.54s/it]
Requested to load AutoencoderKL
Loading 1 new model
[Fooocus Model Management] Moving model(s) has taken 1.94 seconds
Inswapper: Target index: 0.0
download_path: ./checkpoints\models\buffalo_l
Downloading ./checkpoints\models\buffalo_l.zip from https://github.com/deepinsight/insightface/releases/download/v0.7/buffalo_l.zip...
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 281857/281857 [01:33<00:00, 3000.07KB/s]
2024-02-22 09:33:38.8141340 [E:onnxruntime:Default, provider_bridge_ort.cc:1532 onnxruntime::TryGetProviderInfo_TensorRT] D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1209 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "C:\Users\moath alhssah\AppData\Local\Programs\Python\Python310\lib\site-packages\onnxruntime\capi\onnxruntime_providers_tensorrt.dll"

*************** EP Error ***************
EP Error D:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:456 onnxruntime::python::RegisterTensorRTPluginsAsCustomOps Please install TensorRT libraries as mentioned in the GPU requirements page, make sure they're in the PATH or LD_LIBRARY_PATH, and that your GPU is supported.
 when using ['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider']
Falling back to ['CUDAExecutionProvider', 'CPUExecutionProvider'] and retrying.
****************************************
2024-02-22 09:33:39.1353830 [E:onnxruntime:Default, provider_bridge_ort.cc:1546 onnxruntime::TryGetProviderInfo_CUDA] D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1209 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "C:\Users\moath alhssah\AppData\Local\Programs\Python\Python310\lib\site-packages\onnxruntime\capi\onnxruntime_providers_cuda.dll"

Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: ./checkpoints\models\buffalo_l\1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
2024-02-22 09:33:39.9811181 [E:onnxruntime:Default, provider_bridge_ort.cc:1532 onnxruntime::TryGetProviderInfo_TensorRT] D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1209 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "C:\Users\moath alhssah\AppData\Local\Programs\Python\Python310\lib\site-packages\onnxruntime\capi\onnxruntime_providers_tensorrt.dll"

*************** EP Error ***************
EP Error D:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:456 onnxruntime::python::RegisterTensorRTPluginsAsCustomOps Please install TensorRT libraries as mentioned in the GPU requirements page, make sure they're in the PATH or LD_LIBRARY_PATH, and that your GPU is supported.
 when using ['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider']
Falling back to ['CUDAExecutionProvider', 'CPUExecutionProvider'] and retrying.
****************************************
2024-02-22 09:33:40.0300656 [E:onnxruntime:Default, provider_bridge_ort.cc:1546 onnxruntime::TryGetProviderInfo_CUDA] D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1209 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "C:\Users\moath alhssah\AppData\Local\Programs\Python\Python310\lib\site-packages\onnxruntime\capi\onnxruntime_providers_cuda.dll"

Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: ./checkpoints\models\buffalo_l\2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
2024-02-22 09:33:40.1010470 [E:onnxruntime:Default, provider_bridge_ort.cc:1532 onnxruntime::TryGetProviderInfo_TensorRT] D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1209 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "C:\Users\moath alhssah\AppData\Local\Programs\Python\Python310\lib\site-packages\onnxruntime\capi\onnxruntime_providers_tensorrt.dll"

*************** EP Error ***************
EP Error D:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:456 onnxruntime::python::RegisterTensorRTPluginsAsCustomOps Please install TensorRT libraries as mentioned in the GPU requirements page, make sure they're in the PATH or LD_LIBRARY_PATH, and that your GPU is supported.
 when using ['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider']
Falling back to ['CUDAExecutionProvider', 'CPUExecutionProvider'] and retrying.
****************************************
2024-02-22 09:33:40.1605064 [E:onnxruntime:Default, provider_bridge_ort.cc:1546 onnxruntime::TryGetProviderInfo_CUDA] D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1209 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "C:\Users\moath alhssah\AppData\Local\Programs\Python\Python310\lib\site-packages\onnxruntime\capi\onnxruntime_providers_cuda.dll"

Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: ./checkpoints\models\buffalo_l\det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0
2024-02-22 09:33:40.4148663 [E:onnxruntime:Default, provider_bridge_ort.cc:1532 onnxruntime::TryGetProviderInfo_TensorRT] D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1209 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "C:\Users\moath alhssah\AppData\Local\Programs\Python\Python310\lib\site-packages\onnxruntime\capi\onnxruntime_providers_tensorrt.dll"

*************** EP Error ***************
EP Error D:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:456 onnxruntime::python::RegisterTensorRTPluginsAsCustomOps Please install TensorRT libraries as mentioned in the GPU requirements page, make sure they're in the PATH or LD_LIBRARY_PATH, and that your GPU is supported.
 when using ['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider']
Falling back to ['CUDAExecutionProvider', 'CPUExecutionProvider'] and retrying.
****************************************
2024-02-22 09:33:40.4720848 [E:onnxruntime:Default, provider_bridge_ort.cc:1546 onnxruntime::TryGetProviderInfo_CUDA] D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1209 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "C:\Users\moath alhssah\AppData\Local\Programs\Python\Python310\lib\site-packages\onnxruntime\capi\onnxruntime_providers_cuda.dll"

Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: ./checkpoints\models\buffalo_l\genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0
2024-02-22 09:33:40.5211007 [E:onnxruntime:Default, provider_bridge_ort.cc:1532 onnxruntime::TryGetProviderInfo_TensorRT] D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1209 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "C:\Users\moath alhssah\AppData\Local\Programs\Python\Python310\lib\site-packages\onnxruntime\capi\onnxruntime_providers_tensorrt.dll"

*************** EP Error ***************
EP Error D:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:456 onnxruntime::python::RegisterTensorRTPluginsAsCustomOps Please install TensorRT libraries as mentioned in the GPU requirements page, make sure they're in the PATH or LD_LIBRARY_PATH, and that your GPU is supported.
 when using ['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider']
Falling back to ['CUDAExecutionProvider', 'CPUExecutionProvider'] and retrying.
****************************************
2024-02-22 09:33:40.6631070 [E:onnxruntime:Default, provider_bridge_ort.cc:1546 onnxruntime::TryGetProviderInfo_CUDA] D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1209 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "C:\Users\moath alhssah\AppData\Local\Programs\Python\Python310\lib\site-packages\onnxruntime\capi\onnxruntime_providers_cuda.dll"

Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: ./checkpoints\models\buffalo_l\w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5
set det-size: (320, 320)
2024-02-22 09:33:42.1722514 [E:onnxruntime:Default, provider_bridge_ort.cc:1546 onnxruntime::TryGetProviderInfo_CUDA] D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1209 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "C:\Users\moath alhssah\AppData\Local\Programs\Python\Python310\lib\site-packages\onnxruntime\capi\onnxruntime_providers_cuda.dll"

Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
inswapper-shape: [1, 3, 128, 128]
C:\Users\moath alhssah\AppData\Local\Programs\Python\Python310\lib\site-packages\insightface\utils\transform.py:68: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  P = np.linalg.lstsq(X_homo, Y)[0].T # Affine matrix. 3 x 4
Replacing faces in target image from the left to the right by order
Traceback (most recent call last):
  File "C:\Fooocus-inswapper-main\modules\async_worker.py", line 885, in worker
    handler(task)
  File "C:\Users\moath alhssah\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\moath alhssah\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Fooocus-inswapper-main\modules\async_worker.py", line 837, in handler
    imgs = perform_face_swap(imgs, inswapper_source_image, inswapper_target_image_index)
  File "C:\Fooocus-inswapper-main\modules\face_swap.py", line 17, in perform_face_swap
    from inswapper.restoration import face_restoration,check_ckpts,set_realesrgan,torch,ARCH_REGISTRY,cv2
  File "C:\Fooocus-inswapper-main\inswapper\restoration.py", line 10, in <module>
    from basicsr.utils import imwrite, img2tensor, tensor2img
ModuleNotFoundError: No module named 'basicsr'
Total time: 464.33 seconds

**Comment by machineminded** [comment]
Did you already run `configure.bat`?  If so, then try running the xcopy commands from `configure.bat` while in the root of the Fooocus-inswapper repo:

```
xcopy /E /I /Y inswapper\CodeFormer\CodeFormer\basicsr venv\Lib\site-packages\basicsr
xcopy /E /I /Y inswapper\CodeFormer\CodeFormer\facelib venv\Lib\site-packages\facelib
```

Also be sure your venv is activated with `.\venv\Scripts\activate`.

**Comment by Wolfeyejo** [comment]
hello 
sorry for the late reply, I got this 
C:\Fooocus-inswapper-main>.\venv\Scripts\activate
'.\venv\Scripts\activate' is not recognized as an internal or external command,
operable program or batch file.

C:\Fooocus-inswapper-main>

**Comment by machineminded** [comment]
You need to run configure.bat immediately after cloning the repo.

**Comment by Wolfeyejo** [comment]
I did and got this 

ExpandArchiveHelper : Failed to create file 'C:\Fooocus-inswapper-main\InstantID\models\antelopev2\1k3d68.onnx' while   expanding the archive file 'C:\Fooocus-inswapper-main\InstantID\models\antelopev2.zip' contents as the file             'C:\Fooocus-inswapper-main\InstantID\models\antelopev2\1k3d68.onnx' already exists. Use the -Force parameter if you     want to overwrite the existing directory 'C:\Fooocus-inswapper-main\InstantID\models\antelopev2\1k3d68.onnx' contents   when expanding the archive file.                                                                                        At                                                                                                                      C:\Windows\system32\WindowsPowerShell\v1.0\Modules\Microsoft.PowerShell.Archive\Microsoft.PowerShell.Archive.psm1:397   char:17                                                                                                                 + ...             ExpandArchiveHelper $resolvedSourcePaths $resolvedDestina ...                                         +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                 + CategoryInfo          : InvalidOperation: (C:\Fooocus-insw...ev2\1k3d68.onnx:String) [Write-Error], IOException       + FullyQualifiedErrorId : ExpandArchiveFileExists,ExpandArchiveHelper                                                                                                                                                                       ExpandArchiveHelper : Failed to create file 'C:\Fooocus-inswapper-main\InstantID\models\antelopev2\2d106det.onnx'       while expanding the archive file 'C:\Fooocus-inswapper-main\InstantID\models\antelopev2.zip' contents as the file       'C:\Fooocus-inswapper-main\InstantID\models\antelopev2\2d106det.onnx' already exists. Use the -Force parameter if you   want to overwrite the existing directory 'C:\Fooocus-inswapper-main\InstantID\models\antelopev2\2d106det.onnx'          contents when expanding the archive file.                                                                               At                                                                                                                      C:\Windows\system32\WindowsPowerShell\v1.0\Modules\Microsoft.PowerShell.Archive\Microsoft.PowerShell.Archive.psm1:397   char:17                                                                                                                 + ...             ExpandArchiveHelper $resolvedSourcePaths $resolvedDestina ...                                         +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                 + CategoryInfo          : InvalidOperation: (C:\Fooocus-insw...2\2d106det.onnx:String) [Write-Error], IOException       + FullyQualifiedErrorId : ExpandArchiveFileExists,ExpandArchiveHelper                                                                                                                                                                       ExpandArchiveHelper : Failed to create file 'C:\Fooocus-inswapper-main\InstantID\models\antelopev2\genderage.onnx'      while expanding the archive file 'C:\Fooocus-inswapper-main\InstantID\models\antelopev2.zip' contents as the file       'C:\Fooocus-inswapper-main\InstantID\models\antelopev2\genderage.onnx' already exists. Use the -Force parameter if you  want to overwrite the existing directory 'C:\Fooocus-inswapper-main\InstantID\models\antelopev2\genderage.onnx'         contents when expanding the archive file.                                                                               At                                                                                                                      C:\Windows\system32\WindowsPowerShell\v1.0\Modules\Microsoft.PowerShell.Archive\Microsoft.PowerShell.Archive.psm1:397   char:17                                                                                                                 + ...             ExpandArchiveHelper $resolvedSourcePaths $resolvedDestina ...                                         +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                 + CategoryInfo          : InvalidOperation: (C:\Fooocus-insw...\genderage.onnx:String) [Write-Error], IOException       + FullyQualifiedErrorId : ExpandArchiveFileExists,ExpandArchiveHelper                                                                                                                                                                       ExpandArchiveHelper : Failed to create file 'C:\Fooocus-inswapper-main\InstantID\models\antelopev2\glintr100.onnx'      while expanding the archive file 'C:\Fooocus-inswapper-main\InstantID\models\antelopev2.zip' contents as the file       'C:\Fooocus-inswapper-main\InstantID\models\antelopev2\glintr100.onnx' already exists. Use the -Force parameter if you  want to overwrite the existing directory 'C:\Fooocus-inswapper-main\InstantID\models\antelopev2\glintr100.onnx'         contents when expanding the archive file.                                                                               At
C:\Windows\system32\WindowsPowerShell\v1.0\Modules\Microsoft.PowerShell.Archive\Microsoft.PowerShell.Archive.psm1:397
char:17
+ ...             ExpandArchiveHelper $resolvedSourcePaths $resolvedDestina ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (C:\Fooocus-insw...\glintr100.onnx:String) [Write-Error], IOException
    + FullyQualifiedErrorId : ExpandArchiveFileExists,ExpandArchiveHelper

ExpandArchiveHelper : Failed to create file
'C:\Fooocus-inswapper-main\InstantID\models\antelopev2\scrfd_10g_bnkps.onnx' while expanding the archive file
'C:\Fooocus-inswapper-main\InstantID\models\antelopev2.zip' contents as the file
'C:\Fooocus-inswapper-main\InstantID\models\antelopev2\scrfd_10g_bnkps.onnx' already exists. Use the -Force parameter
if you want to overwrite the existing directory
'C:\Fooocus-inswapper-main\InstantID\models\antelopev2\scrfd_10g_bnkps.onnx' contents when expanding the archive file.
At
C:\Windows\system32\WindowsPowerShell\v1.0\Modules\Microsoft.PowerShell.Archive\Microsoft.PowerShell.Archive.psm1:397
char:17
+ ...             ExpandArchiveHelper $resolvedSourcePaths $resolvedDestina ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (C:\Fooocus-insw..._10g_bnkps.onnx:String) [Write-Error], IOException
    + FullyQualifiedErrorId : ExpandArchiveFileExists,ExpandArchiveHelper

**Comment by machineminded** [comment]
It looks like it is failing because the directories already exist and PowerShell doesn't like that.  Can you try updating the configure.bat to provide the -Force option during the expand operation?
