### ISSUE TITLE
ImportError: Unable to import 'IOComponent' from 'gradio.components.base'

### ISSUE THREAD

**Issue by dietgar** [machineminded/Fooocus-inswapper#26]
python .\launch.py

[System ARGV] ['.\\launch.py']
Python 3.11.4 (tags/v3.11.4:d2340ef, Jun  7 2023, 05:45:37) [MSC v.1934 64 bit (AMD64)]
Fooocus version: 2.1.865
Traceback (most recent call last):
  File "C:\Users\mrdie\Documents\FocusImswapper\Fooocus-inswapper\launch.py", line 128, in <module>
    from webui import *
  File "C:\Users\mrdie\Documents\FocusImswapper\Fooocus-inswapper\webui.py", line 14, in <module>
    import modules.gradio_hijack as grh
  File "C:\Users\mrdie\Documents\FocusImswapper\Fooocus-inswapper\modules\gradio_hijack.py", line 21, in <module>
    from gradio.components.base import IOComponent, _Keywords, Block
ImportError: cannot import name 'IOComponent' from 'gradio.components.base' (C:\Users\mrdie\Documents\FocusImswapper\Fooocus-inswapper\venv\Lib\site-packages\gradio\components\base.py)

**Comment by machineminded** [comment]
I guess try installing gradio with pip install gradio.  Make sure you are running the configure.bat if you're on windows.
