### ISSUE TITLE
[Bug]: InstantID:AssertionError

### ISSUE THREAD

**Issue by Amit30swgoh** [machineminded/Fooocus-inswapper#32]
### Checklist

- [X] The issue has not been resolved by following the [troubleshooting guide](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md)
- [X] The issue exists on a clean installation of Fooocus
- [X] The issue exists in the current version of Fooocus
- [X] The issue has not been reported before recently
- [X] The issue has been reported before but has not been fixed yet

### What happened?

InstantID: ENABLED
[Parameters] Adaptive CFG = 7
[Parameters] Sharpness = 2
[Parameters] ControlNet Softness = 0.25
[Parameters] ADM Scale = 1.5 : 0.8 : 0.3
[Parameters] CFG = 4.0
[Parameters] Seed = 568645601431872844
[Parameters] Sampler = dpmpp_2m_sde_gpu - karras
[Parameters] Steps = 30 - 15
[Fooocus] Initializing ...
[Fooocus] Loading models ...
Refiner unloaded.
Request to load LoRAs [['None', 0.1], ['None', 1.0], ['None', 1.0], ['None', 1.0], ['None', 1.0]] for model [/content/Fooocus-inswapper/models/checkpoints/juggernautXL_v8Rundiffusion.safetensors].
Requested to load SDXLClipModel
Requested to load GPT2LMHeadModel
Loading 2 new models
unload clone 0
[Fooocus Model Management] Moving model(s) has taken 1.65 seconds
[Fooocus] Processing prompts ...
[Fooocus] Encoding positive #1 ...
[Fooocus Model Management] Moving model(s) has taken 0.11 seconds
[Fooocus] Encoding positive #2 ...
[Fooocus] Encoding negative #1 ...
[Fooocus] Encoding negative #2 ...
[Parameters] Denoising Strength = 1.0
[Parameters] Initial Latent shape: Image Space (1216, 832)
Preparation time: 1.86 seconds
InstantID: Begin
InstantID: Positive prompt: a photo of a woman
InstantID: Negative prompt: 
InstantID: Loading diffusers pipeline into memory.
Traceback (most recent call last):
  File "/content/Fooocus-inswapper/modules/async_worker.py", line 976, in worker
    handler(task)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/content/Fooocus-inswapper/modules/async_worker.py", line 873, in handler
    imgs = generate_instantid(instantid_image_path, instantid_pose_image_path, instantid_prompt, instantid_negative_prompt, steps, task['task_seed'], width, height, guidance_scale, loras, sampler_name, scheduler_name, async_task, instantid_identitynet_strength_ratio, instantid_adapter_strength_ratio)
  File "/content/Fooocus-inswapper/modules/instantid.py", line 144, in generate_instantid
    pipe = load_model(loras, sampler_name)
  File "/content/Fooocus-inswapper/modules/instantid.py", line 50, in load_model
    app = FaceAnalysis(name='antelopev2', root='InstantID', providers=['CUDAExecutionProvider', 'CPUExecutionProvider'])
  File "/usr/local/lib/python3.10/dist-packages/insightface/app/face_analysis.py", line 43, in __init__
    assert 'detection' in self.models
AssertionError
Total time: 1.91 seconds

### Steps to reproduce the problem

1. !pip install pygit2==1.12.2
%cd /content
!git clone https://github.com/machineminded/Fooocus-inswapper.git
!git checkout feature/instantid
%cd /content/Fooocus-inswapper
!chmod +x configure-colab.sh
!/content/Fooocus-inswapper/configure-colab.sh
# %pip install -r requirements_versions.txt

!python launch.py --share

2. enable instantID 
3. nothing happened and in the log i get AssertionError

### What should have happened?

create instantID generate image

### What browsers do you use to access Fooocus?

Google Chrome

### Where are you running Fooocus?

Cloud (Google Colab)

### Console logs

```Shell
This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from Terminal to deploy to Spaces (https://huggingface.co/spaces)
Inswapper: DISABLED
PhotoMaker: DISABLED
InstantID: ENABLED
[Parameters] Adaptive CFG = 7
[Parameters] Sharpness = 2
[Parameters] ControlNet Softness = 0.25
[Parameters] ADM Scale = 1.5 : 0.8 : 0.3
[Parameters] CFG = 4.0
[Parameters] Seed = 2426708296706601598
[Parameters] Sampler = dpmpp_2m_sde_gpu - karras
[Parameters] Steps = 30 - 15
[Fooocus] Initializing ...
[Fooocus] Loading models ...
Refiner unloaded.
[Fooocus] Processing prompts ...
[Fooocus] Preparing Fooocus text #1 ...
[Prompt Expansion] a photo of a woman, full intricate, elegant, highly detailed, wonderful colors, warm dynamic dramatic beautiful new, relaxed, inspired, breathtaking, creative, vibrant, unique, cute, touching, majestic, delicate, symmetry, innocent, pretty, charming, peaceful, iconic, lovely, very, pure, cinematic, artistic, loving, brave, passionate, cheerful, determined
[Fooocus] Preparing Fooocus text #2 ...
[Prompt Expansion] a photo of a woman, very beautiful, elegant, cinematic, stunning, highly detailed, real, aesthetic, delicate, dramatic, intricate, rich deep colors, attractive, sublime, coherent, passionate, colorful, surreal, pretty, mystical, open, glowing, determined, extremely, focused, breathtaking, incredible detail, creative, positive light, cute, lovely, infinite, symmetry
[Fooocus] Encoding positive #1 ...
[Fooocus Model Management] Moving model(s) has taken 0.12 seconds
[Fooocus] Encoding positive #2 ...
[Fooocus] Encoding negative #1 ...
[Fooocus] Encoding negative #2 ...
[Parameters] Denoising Strength = 1.0
[Parameters] Initial Latent shape: Image Space (896, 1152)
Preparation time: 3.83 seconds
InstantID: Begin
InstantID: Positive prompt: cinematic still a photo of a woman . emotional, harmonious, vignette, 4k epic detailed, shot on kodak, 35mm photo, sharp focus, high budget, cinemascope, moody, epic, gorgeous, film grain, grainy
InstantID: Negative prompt: (worst quality, low quality, normal quality, lowres, low details, oversaturated, undersaturated, overexposed, underexposed, grayscale, bw, bad photo, bad photography, bad art:1.4), (watermark, signature, text font, username, error, logo, words, letters, digits, autograph, trademark, name:1.2), (blur, blurry, grainy), morbid, ugly, asymmetrical, mutated malformed, mutilated, poorly lit, bad shadow, draft, cropped, out of frame, cut off, censored, jpeg artifacts, out of focus, glitch, duplicate, (airbrushed, cartoon, anime, semi-realistic, cgi, render, blender, digital art, manga, amateur:1.3), (3D ,3D Game, 3D Game Scene, 3D Character:1.1), (bad hands, bad anatomy, bad body, bad face, bad teeth, bad arms, bad legs, deformities:1.3)
InstantID: Loading diffusers pipeline into memory.
Traceback (most recent call last):
  File "/content/Fooocus-inswapper/modules/async_worker.py", line 976, in worker
    handler(task)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/content/Fooocus-inswapper/modules/async_worker.py", line 873, in handler
    imgs = generate_instantid(instantid_image_path, instantid_pose_image_path, instantid_prompt, instantid_negative_prompt, steps, task['task_seed'], width, height, guidance_scale, loras, sampler_name, scheduler_name, async_task, instantid_identitynet_strength_ratio, instantid_adapter_strength_ratio)
  File "/content/Fooocus-inswapper/modules/instantid.py", line 144, in generate_instantid
    pipe = load_model(loras, sampler_name)
  File "/content/Fooocus-inswapper/modules/instantid.py", line 50, in load_model
    app = FaceAnalysis(name='antelopev2', root='InstantID', providers=['CUDAExecutionProvider', 'CPUExecutionProvider'])
  File "/usr/local/lib/python3.10/dist-packages/insightface/app/face_analysis.py", line 43, in __init__
    assert 'detection' in self.models
AssertionError
Total time: 3.88 seconds
Inswapper: DISABLED
PhotoMaker: DISABLED
InstantID: ENABLED
[Parameters] Adaptive CFG = 7
[Parameters] Sharpness = 2
[Parameters] ControlNet Softness = 0.25
[Parameters] ADM Scale = 1.5 : 0.8 : 0.3
[Parameters] CFG = 4.0
[Parameters] Seed = 568645601431872844
[Parameters] Sampler = dpmpp_2m_sde_gpu - karras
[Parameters] Steps = 30 - 15
[Fooocus] Initializing ...
[Fooocus] Loading models ...
Refiner unloaded.
Request to load LoRAs [['None', 0.1], ['None', 1.0], ['None', 1.0], ['None', 1.0], ['None', 1.0]] for model [/content/Fooocus-inswapper/models/checkpoints/juggernautXL_v8Rundiffusion.safetensors].
Requested to load SDXLClipModel
Requested to load GPT2LMHeadModel
Loading 2 new models
unload clone 0
[Fooocus Model Management] Moving model(s) has taken 1.65 seconds
[Fooocus] Processing prompts ...
[Fooocus] Encoding positive #1 ...
[Fooocus Model Management] Moving model(s) has taken 0.11 seconds
[Fooocus] Encoding positive #2 ...
[Fooocus] Encoding negative #1 ...
[Fooocus] Encoding negative #2 ...
[Parameters] Denoising Strength = 1.0
[Parameters] Initial Latent shape: Image Space (1216, 832)
Preparation time: 1.86 seconds
InstantID: Begin
InstantID: Positive prompt: a photo of a woman
InstantID: Negative prompt: 
InstantID: Loading diffusers pipeline into memory.
Traceback (most recent call last):
  File "/content/Fooocus-inswapper/modules/async_worker.py", line 976, in worker
    handler(task)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/content/Fooocus-inswapper/modules/async_worker.py", line 873, in handler
    imgs = generate_instantid(instantid_image_path, instantid_pose_image_path, instantid_prompt, instantid_negative_prompt, steps, task['task_seed'], width, height, guidance_scale, loras, sampler_name, scheduler_name, async_task, instantid_identitynet_strength_ratio, instantid_adapter_strength_ratio)
  File "/content/Fooocus-inswapper/modules/instantid.py", line 144, in generate_instantid
    pipe = load_model(loras, sampler_name)
  File "/content/Fooocus-inswapper/modules/instantid.py", line 50, in load_model
    app = FaceAnalysis(name='antelopev2', root='InstantID', providers=['CUDAExecutionProvider', 'CPUExecutionProvider'])
  File "/usr/local/lib/python3.10/dist-packages/insightface/app/face_analysis.py", line 43, in __init__
    assert 'detection' in self.models
AssertionError
Total time: 1.91 seconds
```

**Comment by Amit30swgoh** [comment]
im closeing fixed it with !unzip the file
